### ISSUE TITLE
ディレクトリ構成について

### ISSUE THREAD

**Issue by shirakiyo** [tensaitensai/TimeUS-api#5]
https://github.com/golang-standards/project-layout

もし面倒でなければこのディレクトリ構成でプロジェクトを進めるといいかも
この構成のプロジェクトはかなり多いから慣れておいて損はないはず

**Comment by tensaitensai** [comment]
了解しました！！

**Comment by shirakiyo** [comment]
修正する前にクローズしないでください...

**Comment by tensaitensai** [comment]
ごめんなさい
